### PR TITLE
Add pull request template reminding to use drafts as necessary

### PR DESCRIPTION
**Pull request by dopplershift**
Closes ProjectPythia/projectpythia.github.io#184.

### CODE REVIEW

**Review by brian-rose — APPROVED** [review]

**Review by kmpaul — COMMENTED** [review]
Should this be a "comment"?  So we don't get all of our PRs generated with the same content?

**Comment by dopplershift** [comment]
@kmpaul Good call.

**Comment by dopplershift** [comment]
@kmpaul Updated.

**Review by kmpaul — APPROVED** [review]
Awesome!  Thanks, @dopplershift!

**Review by brian-rose — APPROVED** [review]

**Pull request merged**
